-- 20530
SELECT COUNT(*)
FROM trips
WHERE DATE(lpep_dropoff_datetime) = '2019-01-15' 
	AND DATE(lpep_pickup_datetime) = '2019-01-15'



-- 2019-01-15
SELECT DATE(LPEP_PICKUP_DATETIME),
	MAX(TRIP_DISTANCE)
FROM TRIPS
GROUP BY DATE(LPEP_PICKUP_DATETIME)
ORDER BY MAX DESC 



-- depends on how you measure, TODAY, but 2: 1282 ; 3: 254
SELECT PASSENGER_COUNT,
	COUNT(*)
FROM TRIPS
WHERE DATE(LPEP_PICKUP_DATETIME) = '2019-01-01'
	AND PASSENGER_COUNT IN (2,3)
GROUP BY PASSENGER_COUNT 


-- Long Island City/Queens Plaza
SELECT DOZ.ZONE
FROM TRIPS TT
INNER JOIN ZONES PUZ ON TT.PULOCATIONID = PUZ.LOCATIONID
INNER JOIN ZONES DOZ ON TT.DOLOCATIONID = DOZ.LOCATIONID
WHERE PUZ.ZONE = 'Astoria'
ORDER BY TIP_AMOUNT DESC
LIMIT 1